language: cpp
compiler:
  - gcc

env:
  - PATH=/opt/qt5/bin:/opt/hawaii/bin:$PATH
  - LD_LIBRARY_PATH=/opt/qt5/lib:/opt/hawaii/lib:$LD_LIBRARY_PATH

before_install:
  - yes | sudo add-apt-repository ppa:plfiorini/cmake
  - yes | sudo add-apt-repository ppa:canonical-qt5-edgers/qt5-daily
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake qt5-meta-full
  - git submodule update --init --recursive

script: "./compile --prefix=/opt/hawaii --linux-fhs"

branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "irc.freenode.net#maui-project"
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
