language: cpp
compiler:
  - gcc

env:
  - PATH=/opt/qt5/bin:/opt/hawaii/bin:$PATH LD_LIBRARY_PATH=/opt/qt5/lib:/opt/hawaii/lib:$LD_LIBRARY_PATH

before_install:
  # Install CMake and Qt 5
  - yes | sudo add-apt-repository ppa:plfiorini/cmake
  - yes | sudo add-apt-repository ppa:canonical-qt5-edgers/qt5-daily
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake qt5-meta-full
  # Install Solid dependencies
  - sudo apt-get install -qq libudev-dev upower udisks
  # Install Vibe dependencies
  - sudo apt-get install -qq libdconf-dev libdconf-dbus-1-dev libdbus-glib-1-dev libbz2-dev liblzma-dev
  # Install Green Island dependencies
  - sudo apt-get install -qq libgles2-mesa-dev
  # Install Login Manager dependencies
  - sudo apt-get install -qq libpam0g-dev
  # Fetch submodules
  - git submodule update --init --recursive

script: "./compile --prefix=/opt/hawaii --linux-fhs"

branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "irc.freenode.net#maui-project"
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
